extends: relaxed

rules:
  line-length: disable
  trailing-spaces: enable
  indentation:
    spaces: 2
    indent-sequences: consistent
  document-start: disable
  truthy: disable
  comments: disable
  braces: disable
  octal-values: disable
