#!/usr/bin/env python3
"""Generate the per-rule quality matrix in docs/metrics-matrix.md.

Every column comes from a file that already exists:

    rule stem          Detections/*.yaml
    severity           rule YAML
    telemetry tables   rule YAML requiredDataConnectors
    expected volume    rule YAML metadata.expectedVolume (written by the rule's author)
    validation status  tests/validation/atomics.yaml
    test method        tests/validation/atomics.yaml (atomic citations vs manual procedure)

The measurement columns — events evaluated, alerts, true positives, false positives,
precision, FP rate, alert volume per day, detection latency, MTTA, MTTR, suppression
rate, closure reason — are emitted as `Not yet measured` because that is what they
are. They are columns of a framework, not of a report: this repository has no
deployed rule and no closed incident, so there is nothing to put in them. When a
deployment produces them, they are recorded in
tests/validation/performance-metrics.md, not typed into this table.

Generating the matrix is the point. It was hand-written once and silently lost six
rules when the pack grew; a table whose columns are derivable must be derived.

Usage
-----
    python scripts/generate_metrics_matrix.py
    python scripts/generate_metrics_matrix.py --check     # fail if the file is stale
"""
from __future__ import annotations

import argparse
import pathlib
import sys

import yaml

REPO = pathlib.Path(__file__).resolve().parent.parent
DETECTIONS = REPO / "Detections"
LEDGER = REPO / "tests" / "validation" / "atomics.yaml"
OUTPUT = REPO / "docs" / "metrics-matrix.md"

# The framework's measurement columns. Each is written as NOT MEASURED below,
# because that is the state of every rule in this repository.
MEASUREMENT_COLUMNS = [
    "Events evaluated",
    "Alerts",
    "True positives",
    "False positives",
    "Precision",
    "FP rate",
    "Alert volume / day",
    "Latency p95",
    "MTTA",
    "MTTR",
    "Suppression rate",
]
NOT_MEASURED = "Not yet measured"


def clean(text: str) -> str:
    """Rule metadata is written as wrapped prose; a table cell needs one line."""
    return " ".join(str(text).split())


def ledger_index() -> dict:
    ledger = yaml.safe_load(LEDGER.read_text(encoding="utf-8"))
    return {entry["rule"]: entry for entry in ledger["rules"]}


def test_method(entry: dict) -> str:
    """How the rule would be exercised, quoting the ledger rather than restating it."""
    checks = entry.get("checks") or []
    triggers = [c for c in checks if c.get("role") == "trigger"]
    partials = [c for c in checks if c.get("role") == "partial"]
    if triggers:
        cites = ", ".join(f"`{c['technique']}-{c['atomic']}`" for c in triggers)
        if partials:
            cites += f" (+{len(partials)} partial)"
        return f"Atomic Red Team: {cites}"
    if entry.get("manual_procedure"):
        method = "Manual procedure"
        if partials:
            method += f" (+{len(partials)} partial atomic noted)"
        return method
    return "**none — no trigger path**"


def build() -> str:
    ledger = ledger_index()
    rows = []
    for path in sorted(DETECTIONS.glob("*.yaml")):
        rule = yaml.safe_load(path.read_text(encoding="utf-8"))
        meta = rule.get("metadata") or {}
        entry = ledger.get(path.stem)
        if entry is None:
            raise SystemExit(f"{path.stem} has no ledger entry — cannot build the matrix")
        tables = sorted({t for c in rule.get("requiredDataConnectors") or []
                         for t in (c.get("dataTypes") or [])})
        rows.append({
            "rule": path.stem,
            "name": rule["name"],
            "severity": rule["severity"],
            "tables": ", ".join(f"`{t}`" for t in tables),
            "volume": clean(meta.get("expectedVolume", "")),
            "status": entry["status"],
            "method": test_method(entry),
        })

    lines = [
        "# Detection quality matrix — per rule",
        "",
        "Generated by `scripts/generate_metrics_matrix.py`. **Do not edit.** CI regenerates it and",
        "fails if the committed file differs, so a rule added to `Detections/` cannot be missing here.",
        "",
        f"- **Rules:** {len(rows)} scheduled analytics rules",
        f"- **Validation status:** {sorted({r['status'] for r in rows})[0]} for all {len(rows)} — see",
        "  [`../tests/atomics.md`](../tests/atomics.md)",
        "- **Measurement columns:** every one reads `Not yet measured` because no rule has been",
        "  deployed and no incident has been closed. The procedure that fills them, and the queries it",
        "  uses, are in [`../tests/validation/performance-metrics.md`](../tests/validation/performance-metrics.md).",
        "",
        "## Detection quality",
        "",
        "| Rule | Severity | Telemetry | Expected volume (stated by the author, unmeasured) | How it would be exercised | Status |",
        "|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| `{r['rule']}`<br>{r['name']} | {r['severity']} | {r['tables']} | {r['volume']} "
            f"| {r['method']} | {r['status']} |")

    lines += [
        "",
        "## Measurement framework",
        "",
        "The columns below are the agreed field set. They are deliberately **empty of values**: each",
        "one requires a deployed rule and closed incidents, and inventing a number would be worse than",
        "leaving it blank. Definitions and the KQL that produces each column live in",
        "[`../tests/validation/performance-metrics.md`](../tests/validation/performance-metrics.md).",
        "",
        "| Field | Definition | Source |",
        "|---|---|---|",
        "| Events evaluated | Rows the rule's query scanned in the window | Workspace query cost / `Usage` table |",
        "| Alerts | Alerts the rule produced | `SecurityAlert` |",
        "| True positives | Closures classified a true positive | `SecurityIncident.Classification` |",
        "| False positives | Closures classified a false positive | `SecurityIncident.Classification` |",
        "| Precision | TP ÷ (TP + FP), on ≥ 5 closures | Derived from the two rows above |",
        "| FP rate | FP ÷ (TP + FP), on ≥ 5 closures | Derived |",
        "| Alert volume / day | Alerts per calendar day | `SecurityAlert` grouped by `TimeGenerated` |",
        "| Latency p95 | Event time → alert time, 95th percentile | `FirstActivityTime` → `TimeGenerated` |",
        "| MTTA | Incident created → first owner assignment | `CreatedTime` → `FirstModifiedTime` |",
        "| MTTR | Incident created → closed | `CreatedTime` → `ClosedTime` |",
        "| Suppression rate | Alerts suppressed by tuning rather than by detection | `metadata.suppression` decisions per rule |",
        "| Closure reason | Why an incident was closed | `SecurityIncident.Classification` and `ClassificationComment` |",
        "",
        "## How a value gets into this file",
        "",
        "1. Deploy the rule and let it run for a measurement window (30 days is the reference window).",
        "2. Run the query for the field in `tests/validation/performance-metrics.md`.",
        "3. Record the observation, its window and its workspace in that file — **not** in this",
        "   generated table, which is about the rules, not about one tenant's data.",
        "4. If the number changes how the rule should be tuned, that is a tuning-log entry, and the",
        "   rule's `metadata.tuningGuidance` is where the reasoning goes.",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true",
                        help="do not write; fail if the committed file is out of date")
    args = parser.parse_args(argv)

    content = build()
    if args.check:
        if not OUTPUT.exists():
            print(f"::error::docs/{OUTPUT.name} does not exist")
            return 1
        if OUTPUT.read_text(encoding="utf-8") != content:
            print(f"::error::docs/{OUTPUT.name} is stale. Run scripts/generate_metrics_matrix.py")
            return 1
        rules = content.count("\n| `")
        print(f"docs/{OUTPUT.name} matches the rule files and the ledger ({rules} rules)")
        return 0

    OUTPUT.write_text(content, encoding="utf-8")
    print(f"wrote docs/{OUTPUT.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
