#!/usr/bin/env python3
"""Generate tests/atomics.md from tests/validation/atomics.yaml.

The YAML is the machine-readable ledger; this script renders the human-readable
view of it and resolves every cited Atomic Test Index to the upstream test name
from the vendored scripts/atomic_data.json. Generating the table means the two
cannot disagree, and it means a rule cannot quietly drop out of the ledger: CI
re-runs this script and fails on any diff.
"""
from __future__ import annotations

import json
import pathlib
import sys

import yaml

REPO = pathlib.Path(__file__).resolve().parent.parent
LEDGER = REPO / "tests" / "validation" / "atomics.yaml"
ATOMIC_DATA = REPO / "scripts" / "atomic_data.json"
OUT = REPO / "tests" / "atomics.md"

STATUS_ORDER = ["VALIDATED IN LIVE TENANT", "SIMULATED", "STATIC VALIDATION", "NOT YET VALIDATED"]


def load_yaml(path: pathlib.Path) -> dict:
    if not path.exists():
        raise SystemExit(f"::error::missing {path.relative_to(REPO)}")
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def rule_summary(path: pathlib.Path) -> dict:
    data = load_yaml(path)
    return {
        "name": data.get("name", path.stem),
        "techniques": [str(t) for t in (data.get("relevantTechniques") or [])],
    }


def atomic_name(atomic_db: dict, technique: str, index: int) -> str:
    for test in atomic_db.get("techniques", {}).get(technique, []):
        if test["index"] == index:
            return test["name"]
    return "**UNKNOWN — not present in the vendored atomic index**"


def render() -> str:
    ledger = load_yaml(LEDGER)
    atomic_db = json.loads(ATOMIC_DATA.read_text(encoding="utf-8"))

    detections = {p.stem: p for p in sorted((REPO / "Detections").glob("*.yaml"))}
    hunts = {p.stem: p for p in sorted((REPO / "Hunting Queries").glob("*.yaml"))}
    files = {**detections, **hunts}

    entries = ledger.get("rules") or []
    by_status: dict[str, list[str]] = {s: [] for s in STATUS_ORDER}
    for entry in entries:
        by_status.setdefault(entry.get("status", "NOT YET VALIDATED"), []).append(entry["rule"])

    lines: list[str] = []
    lines.append("# Validation Ledger")
    lines.append("")
    lines.append("Auto-generated by `scripts/generate_atomics_ledger.py` from "
                 "`tests/validation/atomics.yaml`. Do not edit by hand.")
    lines.append("")
    lines.append(f"- **Rules covered:** {len(entries)} "
                 f"({len(detections)} scheduled analytics rules, {len(hunts)} hunting queries)")
    lines.append(f"- **Ledger schema:** `tests/validation/validation-schema.yaml` "
                 f"v{ledger.get('schema_version', '?')} · last reviewed "
                 f"{ledger.get('last_reviewed', 'unknown')}")
    lines.append(f"- **Atomic source:** `{ledger.get('source', 'unknown')}` "
                 f"(vendored snapshot: `scripts/atomic_data.json`)")

    status_bits = []
    for status in STATUS_ORDER:
        rules = by_status.get(status) or []
        if rules:
            status_bits.append(f"{len(rules)} {status}")
    lines.append(f"- **Status:** {' · '.join(status_bits)}")
    lines.append("")

    if by_status.get("VALIDATED IN LIVE TENANT"):
        lines.append("> Rules in this ledger marked **VALIDATED IN LIVE TENANT** were executed against a "
                     "live tenant and reviewed by a human; the evidence record for each is named in its "
                     "row. Rules marked **STATIC VALIDATION** have passed CI only and have **not** been "
                     "proven to detect anything.")
    else:
        lines.append("> **No detection in this repository has been executed against a live tenant by the "
                     "author.** Every rule below is at `STATIC VALIDATION`: it passes schema, KQL lint, "
                     "ATT&CK coherence, telemetry-to-connector parity and metadata checks in CI, and "
                     "nothing more. The `Trigger` column says how the rule would be exercised "
                     "(`SIMULATED` or `VALIDATED IN LIVE TENANT`), and the procedure for doing so is in "
                     "`tests/validation/live-validation-guide.md`.")
    lines.append("")

    lines.append("## Ledger")
    lines.append("")
    lines.append("| Rule | Kind | Techniques | Method | Atomic tests | Evidence | Status |")
    lines.append("|---|---|---|---|---|---|---|")

    for entry in entries:
        stem = entry["rule"]
        path = files.get(stem)
        summary = rule_summary(path) if path else {"name": stem, "techniques": []}
        kind = "detection" if stem in detections else ("hunt" if stem in hunts else "unknown")

        triggers, preconditions, partials = [], [], []
        for check in entry.get("checks") or []:
            technique = check.get("technique", "?")
            index = check.get("atomic")
            role = check.get("role", "?")
            label = f"`{technique}`" if index is None else f"`{technique}-{index}`"
            if index is not None:
                label += f" — {atomic_name(atomic_db, technique, index)}"
            if role == "trigger":
                triggers.append(label)
            elif role == "precondition":
                preconditions.append(label)
            else:
                partials.append(label + (f" _(partial: {check['note']})_" if check.get("note") else ""))

        if triggers:
            method = "Atomic Red Team"
        elif preconditions or partials:
            method = "Manual procedure (atomically incomplete)"
        else:
            method = "Manual procedure"

        parts = []
        if triggers:
            parts.append("**Trigger**<br>" + "<br>".join(triggers))
        if preconditions:
            parts.append("**Precondition**<br>" + "<br>".join(preconditions))
        if partials:
            parts.append("**Partial**<br>" + "<br>".join(partials))
        atomic_cell = "<br><br>".join(parts) if parts else "—"

        if entry.get("manual_procedure"):
            procedure = " ".join(str(entry["manual_procedure"]).split())
            method += f"<br><br>{procedure}"

        notes = " ".join(str(entry.get("notes", "")).split())
        evidence = " ".join(str(entry.get("evidence", "")).split())
        evidence_cell = evidence if not notes else f"{evidence}<br><br>{notes}"

        lines.append(
            f"| `{stem}`<br>{summary['name']} | {kind} | "
            f"{', '.join('`' + t + '`' for t in summary['techniques']) or '—'} | {method} | "
            f"{atomic_cell} | {evidence_cell} | {entry.get('status', 'UNKNOWN')} |"
        )

    lines.append("")
    lines.append("## Techniques with no upstream atomics")
    lines.append("")
    without = atomic_db.get("techniques_without_atomics") or []
    lines.append("These techniques are referenced by rules in this repository, and Atomic Red Team "
                 "publishes no test for them. A rule mapped to one of these techniques can only be "
                 "validated with a written manual procedure: " + ", ".join(f"`{t}`" for t in without) + ".")
    lines.append("")
    lines.append("## Reading a status")
    lines.append("")
    lines.append("| Status | Meaning |")
    lines.append("|---|---|")
    lines.append("| `STATIC VALIDATION` | Passes CI checks. Nothing has been executed. |")
    lines.append("| `SIMULATED` | Exercised against deliberately produced telemetry outside production, "
                 "with a dated evidence record. |")
    lines.append("| `VALIDATED IN LIVE TENANT` | Fired on real telemetry in an authorised tenant, with the "
                 "incident reviewed by a human and a dated evidence record. |")
    lines.append("| `NOT YET VALIDATED` | In the repository, not yet statically validated or executed. |")
    lines.append("")
    lines.append("Status definitions and evidence requirements live in "
                 "`tests/validation/validation-schema.yaml`. The procedure for moving a rule from "
                 "`STATIC VALIDATION` to `SIMULATED` or `VALIDATED IN LIVE TENANT` is in "
                 "`tests/validation/live-validation-guide.md`, and the record format is "
                 "`tests/validation/evidence-template.md`.")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    rendered = render()
    current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
    OUT.write_text(rendered, encoding="utf-8")
    action = "unchanged" if current == rendered else "updated"
    print(f"{OUT.relative_to(REPO)} {action} "
          f"({len(rendered.splitlines())} lines, {rendered.count('| `')} rows)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
