#!/usr/bin/env python3
"""
Parse every YAML rule under Detections/ and Hunting Queries/, then emit:
  - coverage.md                  (Markdown ATT&CK matrix)
  - attack-navigator/layer.json  (drop into mitre-attack.github.io/attack-navigator)

Requires pyyaml (installed by CI). Run from repo root:
  python scripts/generate_coverage.py

CI fails if the regenerated files differ from what is committed (drift check).
"""
from __future__ import annotations

import json
import sys
from collections import defaultdict
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
RULE_DIRS = [REPO / "Detections", REPO / "Hunting Queries"]
COVERAGE_MD = REPO / "coverage.md"
LAYER_JSON = REPO / "attack-navigator" / "layer.json"


def collect() -> list[dict]:
    rules = []
    for d in RULE_DIRS:
        if not d.is_dir():
            continue
        for path in sorted(d.glob("*.yaml")):
            try:
                meta = yaml.safe_load(path.read_text(encoding="utf-8"))
            except Exception as exc:
                print(f"WARN: failed to parse {path}: {exc}", file=sys.stderr)
                continue
            if not isinstance(meta, dict):
                continue
            rules.append({
                "file": path.relative_to(REPO).as_posix(),
                "name": meta.get("name", path.stem),
                "kind": "Detection" if d.name == "Detections" else "Hunt",
                "severity": meta.get("severity", "—"),
                "tactics": meta.get("tactics") or [],
                "techniques": [str(t) for t in meta.get("relevantTechniques") or []],
            })
    return rules


def write_coverage_md(rules: list[dict]) -> None:
    by_tech: dict[str, list[dict]] = defaultdict(list)
    for r in rules:
        for t in r["techniques"]:
            by_tech[t].append(r)
    all_tactics = sorted({t for r in rules for t in r["tactics"]})
    lines = [
        "# ATT&CK Coverage",
        "",
        "Auto-generated by `scripts/generate_coverage.py`. Do not edit by hand.",
        "",
        f"- **Rules:** {sum(1 for r in rules if r['kind']=='Detection')} detections + "
        f"{sum(1 for r in rules if r['kind']=='Hunt')} hunts",
        f"- **Unique techniques:** {len(by_tech)}",
        f"- **Tactics covered:** {len(all_tactics)} ({', '.join(all_tactics)})",
        "",
        "Technique IDs are validated against the vendored ATT&CK dataset "
        "(`scripts/attack_data.json`, built from MITRE CTI) by `scripts/ci_validate.py`.",
        "",
        "## Techniques → Rules",
        "",
        "| Technique | Rule | Type | Severity |",
        "|---|---|---|---|",
    ]
    for tech in sorted(by_tech):
        for r in by_tech[tech]:
            lines.append(f"| `{tech}` | [{r['name']}]({r['file']}) | {r['kind']} | {r['severity']} |")
    COVERAGE_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {COVERAGE_MD.relative_to(REPO)}")


def write_navigator_layer(rules: list[dict]) -> None:
    by_tech: dict[str, list[dict]] = defaultdict(list)
    for r in rules:
        for t in r["techniques"]:
            by_tech[t].append(r)
    techniques = []
    for tech in sorted(by_tech):
        hits = by_tech[tech]
        comment = "; ".join(f"{r['name']} ({r['kind']})" for r in hits)
        techniques.append({
            "techniqueID": tech,
            "score": min(100, 25 * len(hits)),
            "color": "",
            "comment": comment,
            "enabled": True,
        })
    layer = {
        "name": "sentinel-detection-engine coverage",
        "versions": {"attack": "18", "navigator": "5.1.0", "layer": "4.5"},
        "domain": "enterprise-attack",
        "description": "ATT&CK coverage produced by github.com/sandeepmothukuri/sentinel-detection-engine",
        "techniques": techniques,
        "gradient": {
            "colors": ["#dde4ee", "#2776d6", "#0d3a76"],
            "minValue": 0,
            "maxValue": 100,
        },
        "legendItems": [
            {"label": "1 rule",  "color": "#dde4ee"},
            {"label": "2 rules", "color": "#2776d6"},
            {"label": "3+ rules","color": "#0d3a76"},
        ],
    }
    LAYER_JSON.parent.mkdir(parents=True, exist_ok=True)
    LAYER_JSON.write_text(json.dumps(layer, indent=2), encoding="utf-8")
    print(f"Wrote {LAYER_JSON.relative_to(REPO)}")


def main() -> int:
    rules = collect()
    if not rules:
        print("No rules found.", file=sys.stderr)
        return 1
    write_coverage_md(rules)
    write_navigator_layer(rules)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
