#!/usr/bin/env python3
"""
Package the rule YAML without its authoring metadata block.

This repo's rule files carry a human-facing `metadata:` block (false positives,
tuning guidance, validation status) alongside the analytics-rule fields. That
block is documentation about the rule, not part of the rule, so a consumer that
wants the rule alone — a reviewer, or a diff against the portal's export format —
gets a clean copy under dist/sentinel-yaml/ here.

Not to be confused with the deployment path: a Sentinel Repositories (GitOps)
connection deploys ARM templates, which are generated by
scripts/generate_arm_templates.py into deploy/. This script produces YAML.

Run from repo root: python scripts/package_rules.py
"""
from __future__ import annotations

import shutil
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "dist" / "sentinel-yaml"


def main() -> int:
    if OUT.exists():
        shutil.rmtree(OUT)
    total = 0
    for d in ("Detections", "Hunting Queries"):
        src_dir = REPO / d
        dst_dir = OUT / d
        dst_dir.mkdir(parents=True, exist_ok=True)
        for path in sorted(src_dir.glob("*.yaml")):
            data = yaml.safe_load(path.read_text(encoding="utf-8"))
            data.pop("metadata", None)
            (dst_dir / path.name).write_text(
                yaml.safe_dump(data, sort_keys=False, allow_unicode=True),
                encoding="utf-8",
            )
            total += 1
    print(f"Packaged {total} rules into {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
